name: Déploiement continu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Déployer sur le VPS
      id: pull-and-deploy
      env:
          DOTNET_ENVIRONMENT: Production
      run: |
        ssh ubuntu@44.201.133.27 "
        cd /home/ubuntu/VoisinUp/ && 
        git pull && 
        dotnet build &&
        dotnet publish -c Release"
