name: Déploiement manuel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement de déploiement'
        required: true
        default: 'DEPLOY'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEPLOY
    steps:
      - name : check secrets
        run : echo ${{ secrets.HOST }}

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # Pull the latest image
            sudo docker pull aqueuse/voisinup:latest

            # Stop and remove the old container
            sudo docker stop voisinup
            sudo docker rm voisinup

            # Run a new container with the latest image
            sudo docker run -d --name voisinup -p 80:80 aqueuse/voisinup:latest
            
